<?php
  require("itemView.php");
?>
<html>
<head>
<title>www.Mostbauer.com - Mostbauern für d' Stodleit von Linz</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta name="keywords" content="Mostbauer, Mostbauern, MostbauernEckn, Eck,Most, Linz, Urfahr, Leonding, Altenberg, Ansfelden, Ebelsberg, Rufling, Pasching, Schmalzbrot, Brettljause, Gastgarten,Mostschank, Fleischbrot, Kartoffelk&auml;sbrot, Stadler, Winkler,Rohrwieser,P&uuml;hringer,Jagerhuber, Eichbauer in Moos,Mur z' Moos,Sommer, Zum 13er Turm, TamesbergerW&ouml;rndl, Rieder zu Ried,Exenschl&auml;ger, Waldschenke,Mayr z' Imberg,Heidi, Kurt, Schneiderbauer, Hammer, Mirellenst&uuml;berl, Reichinger, Schatzbauer, Riener, St&ouml;ger, Mostbauer z'Linz, Aichhorn, Leitner, Weinstadl">
<meta name="description" content="Wie ich zum Mostbauer.com ? Endlich alle Mostbauern für d'Stodleit von Linz auf an Blick ! Damit steht dem urbanen Kulinarium in der nahen Natur nix im Weg ...">
<meta name="robots" content="index,follow">
</head>
<body bgcolor="#FFFFFF" link="#FFFFFF" vlink="#FFFFFF" alink="#006600">
<table width="100%" border="0" cellpadding="0" cellspacing="0" bgcolor="">
  <tr valign="top"> 
    <td height="71" background="../images/title.jpg" width="799" valign="top"> 
      <div align="right"></div></td>
    <td height="71" background="../images/title-blass.jpg">&nbsp;</td>
  </tr>
  <tr valign="top"> 
    <td width="799" height="13" bgcolor="#669900"> <div align="left"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#FFFFFF"><b><img src="../images/spacer.gif" width="10" height="10" border="0"><img src="../images/ico_birne.gif" width="15" height="15" align="absmiddle"></b></font><font face="Verdana, Arial, Helvetica, sans-serif" size="2"> 
        <img src="../images/square-full.gif" width="7" height="7"><img src="../images/square-full.gif" width="7" height="7"> 
        <strong><a href="index.htm">Home</a><font color="#FFFFFF"> </font></strong><img src="../images/square.gif" width="7" height="7"> 
        </font><font face="Verdana, Arial, Helvetica, sans-serif" size="2"> <b><a href="schmalzbrot-home.htm">Bauern</a></b> 
        <font size="2"><img src="../images/square.gif" width="7" height="7"></font> 
        <a href="most-mania-home.htm"><font color="#FFFFFF"><b>Most-Mania</b></font></a> 
        <font size="2"><img src="../images/square.gif" width="7" height="7"></font> 
        <b><a href="ueber.htm">Über d'Eckn</a> </b></font><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#FFFFFF"><b><img src="../images/spacer.gif" width="260" height="10" border="0"><a href="../ma/index.htm"><img src="../images/ico_birne_ma_grau.gif" alt="Mundoat aktivieren" width="15" height="15" border="0" align="absmiddle"></a><img src="../images/ico_birne_hd.gif" alt="Hochdeitsch umschalten" width="15" height="15" border="0" align="absmiddle"></b></font></div></td>
    <td height="13" valign="middle" nowrap bgcolor=""><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#FFFFFF"><b><img src="../images/spacer.gif" width="10" height="10" border="0"></b></font><font color="#669900" size="1" face="Verdana, Arial, Helvetica, sans-serif">< 
      umschalten Mundart/Hochdeutsch</font></td>
  </tr>
  <tr valign="top"> 
    <td width="799" bgcolor="#99CC33" height="2" valign="middle"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#FFFFFF"><b><img src="../images/spacer.gif" width="10" height="10" border="0"></b></font><font size="1" face="Verdana, Arial, Helvetica, sans-serif"><strong>Wie 
      i zu mein Mostbauer.com ...</strong></font></td>
    <td height="2" bgcolor="">&nbsp;</td>
  </tr>
  <tr valign="top"> 
    <td width="799" background="../images/higru.jpg"> <table width="800" border="0" cellpadding="0" cellspacing="0">
        <tr> 
          <td width="36" valign="top">&nbsp;</td>
          <td width="764" valign="top"> <font size="1"><br>
            </font> <p><font face="Verdana, Arial, Helvetica, sans-serif" size="4"><b>Servicebereich<br>
              </b></font><font face="Verdana, Arial, Helvetica, sans-serif" size="2">Dieser 
              Bereich steht nur für die auf Mostbauer.com gelisteten Bauern 
              zu Verfügung.</font></p>
            <table width="720" border="0" cellspacing="0" cellpadding="0" bgcolor="#00CC00">
              <tr valign="top"> 
                <td> <table width="725" border="0" cellpadding="0" cellspacing="1">
                    <tr bgcolor="#99CC33"> 
                      <td valign="top" bgcolor="#99FF00"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><font color="#FFFFFF" size="2" face="Verdana, Arial, Helvetica, sans-serif"><b><img src="../images/spacer.gif" width="10" height="10" border="0"></b></font><b>Was 
                        möchten Sie tun ?</b></font></td>
                    </tr>
                    <tr bgcolor="#ACFF59"> 
                      <td valign="top" bgcolor="#ACFF59"> <br> <table width="701" border="0" cellspacing="0" cellpadding="0">
                          <tr> 
                            <td width="11"><font color="#FFFFFF" size="2" face="Verdana, Arial, Helvetica, sans-serif"><b><img src="../images/spacer.gif" width="10" height="10" border="0"></b></font></td>
                            <td width="676" valign="top"> 
				
<?php
				//passwort  richtig  - dann speichern und erfolgsmneldung			           
				if(isset($passwort)){  				      
				   $itemResult2=mysql_query("SELECT passwort FROM most_bauer WHERE ID=".$betrieb) or die ("Fehler beim Laden der Daten.");				      
				   list($passwortOrig)=mysql_fetch_row($itemResult2);				      
				   if ($passwort==$passwortOrig){				          
				      				          
				      $sqlstatement="UPDATE most_bauer SET text3='".$neuerText."' WHERE ID=".$betrieb;      //speichern 			                  
				      //echo ($sqlstatement);      				          
				      mysql_query($sqlstatement);
				      
   				      echo "<font face='Verdana, Arial, Helvetica, sans-serif' size='2'>";					  
					  echo "<B>&nbsp;&nbsp;Ihr neuer Text wurde erfolgreich gespeichert !</B>";
					  				      
					  }else{
					  echo "hallo";
					  
					  echo "<BR><font face='Verdana, Arial, Helvetica, sans-serif' size='2' color=red>";					  
					  echo "&nbsp;&nbsp;Das Passwort war nicht korrekt!<BR>";
					  echo "<B></font><font size='2' face='Verdana, Arial, Helvetica, sans-serif' color=black>";
					  echo "&nbsp;&nbsp;Ihr neuer Text konnte NICHT gespeichert werden!</B>";
				       }//passwort is ok				     
					   }//isset passwort

				    if(isset($betrieb)){				      
					//Betriebsbezeichnung   				      
					$itemResult=mysql_query("SELECT name FROM most_bauer WHERE ID=".$betrieb) or die ("Fehler beim Laden der Daten.");				      list($name)=mysql_fetch_row($itemResult);
				      echo <<< EOT
                                      <p><font face="Verdana, Arial, Helvetica, sans-serif" size="2"> 				      
									  &nbsp; Mein Betrieb: &nbsp;<B>$name</B> (Nr.:$betrieb)<input type="hidden" name="betrieb" value=$betrieb>
EOT;
				      }else{
				      echo"<p><font face='Verdana, Arial, Helvetica, sans-serif' size='2'>&nbsp; Mein Betrieb:";                                     				      
					  $selectName="betrieb";				      
					  $behaviourType="lo";				      
					  //echo $behaviourType;				      
					  echo createMostbauernDropdownList($selectName,$behaviourType);				      
					  //echo"$abc";
				     }			
	?> 


	<?php 				
				    if (isset($performAction) ){				       
					switch ($whatIwantToDo) {					     
					  case 1:				      		
					  //bestehenden Text einlesen   				      		
					  $itemResult=mysql_query("SELECT text3 FROM most_bauer WHERE ID=".$betrieb) or die ("Fehler beim Laden der Sprüche");				      		
					  list($text3)=mysql_fetch_row($itemResult);
				      		echo <<< EOT

					        <BR>
				      		&nbsp;&nbsp;Sie k&ouml;nnen Ihren Text f&uuml;r die gr&uuml;ne Box &quot;was der Bauer sagt&quot; hier &auml;ndern:<br>
				      		&nbsp;&nbsp;<textarea name="neuerText" rows="10" cols="50">$text3</textarea>
                            <BR>
				      		&nbsp;&nbsp;Passwort: 
                            <input name="passwort" type="password" id="passwort">
				      		<BR><BR>&nbsp;&nbsp;<I>Hinweis:</I> Sollten Sie noch kein Passwort haben für Ihren Betrieb,<BR>&nbsp;&nbsp;einfach mail an <A HREF="mailto:service@Mostbauer.com">service@Mostbauer.com</A></font>
EOT;
						break;					    
						case 2:						
						echo "<BR> Diese Funktion steht noch nicht vollständig zu verfügung";						
						break;					    
						case 3:						
						echo "<BR> Diese Funktion steht noch nicht vollständig zu verfügung";	
						break;
					    default:						
						echo "Keinen Menüpunkt gewählt";				      
						}  //end switch
				    }else{     				      
					//else perform action nicht gesetzt
				      		echo <<< EOT
							
							 <BR>				      
					  <font size="2" face="Verdana, Arial, Helvetica, sans-serif">&nbsp;&nbsp;Ich m&ouml;chte:</font><br>                                      
					  <font size="2" face="Verdana, Arial, Helvetica, sans-serif">                                       
					  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                                       
					  <input name="whatIwantToDo" type="radio" value="1" checked>unseren Text f&uuml;r die gr&uuml;ne Box &quot;was der Bauer sagt&quot; &auml;ndern<br>                                      
					  <BR>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  				      
					  <input type="radio" name="whatIwantToDo" value="2">pflegen von wann bis wann wir Saison haben (reguläre Saison)<br>                                      
					  <BR>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                                       
					  <input type="radio" name="whatIwantToDo" value="3">einen Zeitraum eingeben wo wir währende der Saison geschlossen haben<br>                                      
					  </font><font size="2" face="Verdana, Arial, Helvetica, sans-serif">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;zB kurzer Urlaub währen der Saison...<br>                                      
					  <br>
EOT;
				     }	

	
	?> 


                                  <br>
                                  </font></p>
                                <p>
                                  <input type="submit" name="Submit" value="  OK  ">
                                </p>
                                </form>
                              <br> <font face="Verdana, Arial, Helvetica, sans-serif" size="2">  
                              </font></td>
                            <td width="14"><font color="#FFFFFF" size="2" face="Verdana, Arial, Helvetica, sans-serif"><b><img src="../images/spacer.gif" width="10" height="10" border="0"></b></font></td>
                          </tr>
                        </table>
                        <br> </td>
                    </tr>
                  </table></td>
              </tr>
            </table> 
            <br>
          </td>
        </tr>
      </table></td>
    <td bgcolor="" valign="bottom"> <div align="right"> 
        <p align="left">&nbsp; </p>
        <p> <img src="../images/logo1.gif" width="71" height="137" align="bottom"></p>
      </div></td>
  </tr>
  <tr valign="top"> 
    <td width="799" height="22" valign="middle" bgcolor="#669900"><font size="1"><img src="../images/spacer.gif" width="10" height="10" align="absmiddle"><font face="Verdana, Arial, Helvetica, sans-serif">(c)2004 
      CGint & Chris • <font size="1"><a href="sitemap.htm"><font color="#000000">Seitenübersicht 
      </font></a></font> • <a href="mailto:feedback@mostbauer.com"><font color="#000000">Feedback</font></a> 

      • <a href="../ma/help.htm"><font color="#000000">Hilfe</font></a> • <a href="../ma/kontakt.htm"><font color="#000000">Kontakt</font></a> 
      •<font color="#000000"> </font><font size="1"><font color="#000000">Service</font><font face="Verdana, Arial, Helvetica, sans-serif"> 
      •</font> Stånd:1.1.2005 • www.Mostbauer.com</font></font></font></td>
    <td height="22" bgcolor="">&nbsp;</td>
  </tr>
</table>

<a href="http://t.extreme-dm.com/?login=gintchr4"
target="_top"><img src="http://t1.extreme-dm.com/i.gif"
name="EXim" border="0" alt="eXTReMe Tracker"></img></a> 
<script type="text/javascript" language="javascript1.2"><!--
EXs=screen;EXw=EXs.width;navigator.appName!="Netscape"?
EXb=EXs.colorDepth:EXb=EXs.pixelDepth;//-->
</script><script type="text/javascript"><!--
var EXlogin='gintchr4' // Login
var EXvsrv='s9' // VServer
navigator.javaEnabled()==1?EXjv="y":EXjv="n";
EXd=document;EXw?"":EXw="na";EXb?"":EXb="na";
EXd.write("<img src=\"http://e0.extreme-dm.com",
"/"+EXvsrv+".g?login="+EXlogin+"&amp;",
"jv="+EXjv+"&amp;j=y&amp;srw="+EXw+"&amp;srb="+EXb+"&amp;",
"l="+escape(EXd.referrer)+"\" height=1 width=1>");//-->
</script><noscript><img height="1" width="1" alt=""
src="http://e0.extreme-dm.com/s9.g?login=gintchr4&amp;j=n&amp;jv=n"/>
</noscript>

</body>
</html>

